title:             azx1 
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            azx1
baseurl:           "/azx1.github.io"
url:               "http://azx1.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll
