# Site settings
title: azx1 blog
SEOTitle: 博客 | azx1
header-img: img/home-bg.jpg
email: 1395086733@qq.com
description: "一起发现更大的世界"
keywords: "azx1,azx1's blog, azx1的博客"
url: "http://azx1.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog

#brand info
brand-title: azx1
#brand-icon-type: glyphicon
brand-icon: leaf
#brand-animation-type: animated
brand-animation: swing


# SNS settings
RSS: true
#weibo_username:     AZX1yang
zhihu_username:     azx1
github_username:    azx1
#twitter_username:  azx1
#facebook_username:  azx1



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important




# Analytics settings
# Baidu Analytics
#ba_track_id: a1983936ab86b3e9af8a801d2ea426c9
# Google Analytics
#ga_track_id: 'UA-111647702-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "一起发现更大的世界"
sidebar-avatar: /img/avatar-azx1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Unity manual",
        href: "https://docs.unity3d.com/Manual/UnityManual.html"
    },{
        title: "Bootstrap中文网",
        href: "http://www.bootcss.com/"
    },{
        title: "Liquid手册",
        href: "https://liquid.bootcss.com/"
    },{
        title: "日食记",
        href: "https://h5.youzan.com/v2/showcase/mpnews?alias=YZvuLIHdnh&sf=wx_menu"
    },
]
